fosslight/fosslight_binary_scanner

src/fosslight_binary/_binary.py
Fix a bug related to printing empty column
=> Fix a bug related to printing empty column

.github/workflows/pull-request.yml, src/fosslight_binary/binary_analysis.py
- Fix the bug where there is no start time.
- Modify to run github action for all branches.
=> Fix the bug where there is no start time

src/fosslight_binary/_jar_analysis.py, src/fosslight_binary/binary_analysis.py
Do not print comment if there is no information from OWASP
=> Do not print comment if there is no information from OWASP

requirements.txt, src/fosslight_binary/_binary.py, src/fosslight_binary/_jar_analysis.py, src/fosslight_binary/binary_analysis.py
Add vulnerability column for jar file analysis result
=> Add vulnerability  column for jar file analysis result

src/fosslight_binary/binary_analysis.py
Fix to local variable assignment issue - extended header
=> Fix to local variable assignment issue - extended header

.github/workflows/publish-release.yml
Fix a bug where a warning message to upgrade the version is displayed when the latest version of the executable is executed.
=> Fix to make executable file with latest version

src/fosslight_binary/binary_analysis.py
Return a list of successes and results so that you can call them with the api.
=> Return a list of successes and results

src/fosslight_binary/binary_analysis.py
Change the log level related to the output file.
=> Change the log level related to the output file

.github/workflows/publish-release.yml
Reverts fosslight/fosslight_binary_scanner#40
=> Revert "Develop"

src/fosslight_binary/_jar_analysis.py
- Set CVE valid time to 24 hours
=> Set CVE valid time to 24 hours

LICENSES/LicenseRef-3rd_party_licenses.txt
- Modify LicenseRef-3rd_party_licenses.txt
=> Modify LicenseRef-3rd_party_licenses.txt

src/fosslight_binary/_jar_analysis.py
Even if an OWASP error occurs, modify it to generate result files.
=> Fix the bug where results could not be generated due to OWASP error

src/fosslight_binary/binary_analysis.py
Fix the bug where the entire analysis fails if the magic call fails to check the file type.
=> Add error exception handling when checking file type 

src/fosslight_binary/_binary.py, src/fosslight_binary/binary_analysis.py
- If fetching the binary list fails, exit the program.
- Refactor : Instead of returning list, change it to return a generator.
=> If fetching the binary list fails, exit the program.

.github/workflows/pull-request.yml, src/fosslight_binary/_help.py, src/fosslight_binary/binary_analysis.py
* Add yaml format for FOSSLight Report
* Add a commit message checker
=> Add yaml format for FOSSLight Report

src/fosslight_binary/binary_analysis.py
Let the binary filter be used externally.
=> Let the binary filter be used externally

src/fosslight_binary/binary_analysis.py
Fix a bug where the `current ar archive` file is not considered binary.
=> Fix a bug where the current ar archive file is not considered binary.

requirements.txt
Signed-off-by: Jiyeong Seok <jiyeong.seok@lge.com>
update the minimum version of fosslight_util
=> update the minimum version of fosslight_util

src/fosslight_binary/_jar_analysis.py
- Modify not to generate .jar analysis file
- Remove dependency-check-report.json file after analysis
=> Modify not to generate .jar analysis file

src/fosslight_binary/binary_analysis.py
=> Add progress bar

src/fosslight_binary/binary_analysis.py
If the result file is not created, do not output it to the log.
=> If the result file is not created, do not output it to the log.

src/fosslight_binary/binary_analysis.py
If the path input with -p is null, analyze the path where the command was executed.
=> Analyze the current path if path is null

src/fosslight_binary/_help.py
Remove the required option from the help message
=> Remove the required option from the help message

cli.py, setup.py, src/fosslight_binary/binary_analysis.py, src/fosslight_binary/cli.py, tests/test_fosslight_binary.py
- Modify to use argparse's help msg if invalid input
=> Modify help msg if invalid input

src/fosslight_binary/binary_analysis.py
Separate the function that checks for each file so that it is easy to call the function that checks the binary from the other package.
=> Separate the function that checks binary

src/fosslight_binary/binary_analysis.py, src/fosslight_binary/cli.py
- Remove unnecessary code - print type.
- Change the output file name to fosslight_bin_{ymd_HM}.xlsx from FOSSLight-Report_{Ymd_HMS}.xlsx
=> Remove unnecessary code - print type

src/fosslight_binary/binary_analysis.py
- Modify output file name for opossum
- 'fosslight_opossum_{time}.json'
- 'fosslight_report_{time}.xlsx'
- 'fosslight_log_{time}.txt'
=> Modify output file name for opossum

src/fosslight_binary/cli.py
=> Fix bug without -p option

src/fosslight_binary/binary_analysis.py
Fix memory bug when checking file type.
The previously merged commits are reverted and reflected again.
=> Fix memory bug when checking file type

src/fosslight_binary/binary_analysis.py, tox.ini
=> Change the output file name

src/fosslight_binary/binary_analysis.py
Change yaml output file name to fosslight_report_{datetime}.yaml
=> Change yaml output file name

src/fosslight_binary/_jar_analysis.py
- Modify OSS name from OWASP Result
=> Modify OSS name from OWASP Result

.github/workflows/publish-release.yml, .github/workflows/pull-request.yml, setup.py, src/fosslight_binary/_help.py, src/fosslight_binary/cli.py
Signed-off-by: Jiyeong Seok <jiyeong.seok@lge.com>
Print license text through notice parameter
=> Print license text through notice parameter

src/fosslight_binary/binary_analysis.py
Signed-off-by: Jiyeong Seok <jiyeong.seok@lge.com>
Modify not to generate binary.txt if no binaries
=> Modify not to generate binary.txt if no binaries

src/fosslight_binary/_jar_analysis.py
- Add error handling to analyze jar file
=> Add error handling to analyze jar file

src/fosslight_binary/_jar_analysis.py
- Fix to get OSS info from pkg info
=> Fix to get OSS info from pkg info

src/fosslight_binary/binary_analysis.py
- Add error handling to find file path
=> Add error handling to find file path

src/fosslight_binary/_binary.py
- Modify typo of set_comment in BinaryItem
=> Modify typo of set_comment in BinaryItem

src/fosslight_binary/binary_analysis.py
- Add the pkg name to log and result file
=> Add the pkg name to log and result file

src/fosslight_binary/binary_analysis.py
- Add the package name to opossum result file
=> Add the package name to opossum result file

src/fosslight_binary/_binary.py
- Set comment if ocurs exception when finding binary file
- Add log to debug not bin file
=> Set comment if ocurs exception when finding bin

src/fosslight_binary/_binary.py
Fix the bug that does not print excel.
- Error message : `Fail to generate result file.:Unsupported type <class 'set'> in write()`
=> Fix the bug that does not print excel

src/fosslight_binary/binary_analysis.py
- Exclude .dat file to analyze.
=> Exclude .dat file to analyze

.github/workflows/publish-release.yml, requirements.txt, src/fosslight_binary/_help.py, src/fosslight_binary/binary_analysis.py, src/fosslight_binary/cli.py
Add to correct with sbom-info.yaml
=> Add to correct with sbom-info.yaml

src/fosslight_binary/_help.py, src/fosslight_binary/binary_analysis.py, src/fosslight_binary/cli.py
Change the default path to find sbom-info.yaml
=> Change the default path to find sbom-info.yaml

requirements.txt
Update the minimum version of fl util
=> Update the minimum version of fl util

src/fosslight_binary/binary_analysis.py
- Exclude 'json' and 'js' file when checking if it's binary or not
=> Exclude 'json' and 'js' file

requirements.txt, src/fosslight_binary/_binary.py, src/fosslight_binary/binary_analysis.py
- Add TLSH and checksum column at report
- Hide these columns by default
=> Add TLSH and checksum column at report

requirements.txt, src/fosslight_binary/binary_analysis.py
- Change column name : checksum -> SHA1
=> Change column name : checksum -> SHA1

requirements.txt, src/fosslight_binary/binary_analysis.py
Add detection summary message (cover sheet)
=> Add detection summary message (cover sheet)

requirements.txt, src/fosslight_binary/_binary.py
- Print tlsh, sha1 if no oss info at report
=> Print tlsh, sha1 if no oss info at report

src/fosslight_binary/binary_analysis.py
- Analyze image and icon extension file
- png, gif, jpg, jpeg, bmp, ico
=> Analyze image and icon extension file

src/fosslight_binary/binary_analysis.py
=> Change the cover message

requirements.txt, src/fosslight_binary/_jar_analysis.py, src/fosslight_binary/binary_analysis.py, src/fosslight_binary/cli.py, tox.ini
* Exclude files and directories which user enters from analysis
=> Supports for excluding paths

src/fosslight_binary/_help.py
* Update help message for new argument
=> Update help message

src/fosslight_binary/binary_analysis.py
- Remove related to binary.txt
=> Remove related to binary.txt

src/fosslight_binary/binary_analysis.py
=> Modify column name

src/fosslight_binary/binary_analysis.py
- Bug fix to print column when there is no .jar file
=> Bug fix to print column

src/fosslight_binary/_binary_dao.py, src/fosslight_binary/_jar_analysis.py
- Modify to print binary DB result
- If ths OSS name and OSS version info in OWSAP result, print that.
- Or not, print binary DB result.
=> Modify to print binary DB result

.github/workflows/publish-release.yml, .github/workflows/pull-request.yml, tox.ini
- Bug fix to run executable on WIndows
=> Bug fix to run executable on Windows

src/fosslight_binary/binary_analysis.py
- Exclude specific file and folder
- 'intermediates' folder
- '.class' file
=> Exclude specific file and folder

src/fosslight_binary/binary_analysis.py
- Print option name with error msg
=> Print option name with error msg

src/fosslight_binary/binary_analysis.py
=> Fix to exclude path

src/fosslight_binary/binary_analysis.py
- Convert 'TNULL' to '0' value
=> Convert 'TNULL' to '0' value

src/fosslight_binary/_binary.py
=> Decode vul. url

src/fosslight_binary/binary_analysis.py
- Fix to print excel file by default
=> Fix to print excel file by default

requirements.txt, src/fosslight_binary/binary_analysis.py
- Import exclude path fct. from FL util
- https://github.com/fosslight/fosslight_util/pull/207
=> Import exclude path fct. from FL util
