src/fosslight_binary/_help.py, src/fosslight_binary/binary_analysis.py, tox.ini
Remove remained code related to  -a option
=> Remove remained code related to  -a option

src/fosslight_binary/binary_analysis.py
- Print the extension to the output file of the result log
=> Print the extension to the output file of the result log

requirements.txt, src/fosslight_binary/_jar_analysis.py, src/fosslight_binary/binary_analysis.py
- Modify to print output file name
- Add exit code if there is an error in creating output file
=> Modify to print output file name

src/fosslight_binary/_jar_analysis.py
- Fix to make executable file including 'dependency-check' package
=> Fix to make executable file including 'dependency-check' package

src/fosslight_binary/_jar_analysis.py, src/fosslight_binary/binary_analysis.py
- Add error handle for dependency-check running
=> Add error handle for dependency-check running

src/fosslight_binary/_binary.py, src/fosslight_binary/_binary_dao.py, src/fosslight_binary/binary_analysis.py
=> Apply f-string format

tox.ini
Remove the fixed python version when running tox.
This is to test in python 3.6 or higher.
=> Remove the fixed python version when running tox

src/fosslight_binary/binary_analysis.py
Fix memory bug when checking file type on windows. 
- Error message : 
``` 
[ DEBUG] Failed to check specific file type:fosslight_dependency_scanner-main\fosslight_dependency_scanner-main\tests\test_npm2\node_modules\@babel\core\lib\index.js, b"line I64u: regex error 14 for `^[[:space:]]*class[[:space:]]+[[:digit:][:alpha:]:_]+[[:space:]]*\\{(.*[\n]*)*\\}(;)?$', (failed to get memory)"
```
- How to fix : If an issue of insufficient memory occurs when checking the file type, check the file by reading only 2048 bytes.
=> Fix memory bug when checking file type on windows

tox.ini
- Use allowlist_externals instead of whitelist_externals.
whitelist_externals is now deprecated.
- Add cli to allowlist_externals.
=> Use allowlist_externals instead of whitelist_externals

setup.py
Update package name for ARM Mac.
- Error message when installing pip on Mac M2 chip:
```
The conflict is caused by:
fosslight-binary 4.1.15 depends on python-magic-bin; "darwin" in sys_platform
fosslight-binary 4.1.14 depends on python-magic-bin; "darwin" in sys_platform
fosslight-binary 4.1.13 depends on python-magic-bin; "darwin" in sys_platform
fosslight-binary 4.1.12 depends on python-magic-bin; "darwin" in sys_platform
fosslight-binary 4.1.11 depends on python-magic-bin; "darwin" in sys_platform
fosslight-binary 4.1.10 depends on python-magic-bin; "darwin" in sys_platform
fosslight-binary 4.1.9 depends on python-magic-bin; "darwin" in sys_platform
fosslight-binary 4.1.8 depends on python-magic-bin; "darwin" in sys_platform
fosslight-binary 4.1.7 depends on python-magic-bin; "darwin" …
```
=> Update package name for ARM Mac

src/fosslight_binary/_help.py, src/fosslight_binary/binary_analysis.py, src/fosslight_binary/cli.py
Add simple mode. (-s option)
- If you run in simple mode, you can check the existence of binary and only the binary list as log.
- Execution result of simple mode :
```
% fosslight_binary -p tests -s
[FOSSLIGHT_BINARY] Binaries / Scanned files: 3/11
Binary list:
- tests/askalono_macos
- tests/error_prone_annotations-2.7.1.jar
- tests/test/askalono_macos
Execution result: Success
```
=> Add simple mode (-s option)

src/fosslight_binary/_binary.py, src/fosslight_binary/binary_analysis.py
- Bug fix to print jar analysis.
- AS-IS : As a result of jar file analysis, when there are multiple OSSs, the information for each OSS was not classified. In other words, the two OSS information are connected and output.
- TO-BE: When there are multiple OSS, information on one OSS is divided into a separate list and output as an excel file.
=> Bug fix to print jar analysis

src/fosslight_binary/_binary.py, src/fosslight_binary/_binary_dao.py, src/fosslight_binary/_jar_analysis.py
- Merge oss info result to one row
- If binary's OSS info is in  both OWASP and Binary DB,
- AS-IS : Print both result each row + Exclude Binary DB's result
- TO-BE : Print only one row (OWASP result)
=> Merge OSS info result to one row

requirements.txt, src/fosslight_binary/_help.py, src/fosslight_binary/binary_analysis.py, src/fosslight_binary/cli.py, tox.ini
Enable multiple input for -f option
Example 1)
Command : $fosslight_binary **-o abc/output.xlsx -f csv excel**
Output
- abc/fosslight_log_bin_YYMMDD_HHMM.txt
- abc/output.**csv**
- abc/output.**xlsx**
Example 2)
Command : $fosslight_binary **-o abc -f csv excel**
Output
- abc/fosslight_log_bin_YYMMDD_HHMM.txt
- abc/fosslight_report_bin_YYMMDD_HHMM.**csv**
- abc/fosslight_report_bin_YYMMDD_HHMM.**xlsx**
Example 3)
Command : $fosslight_binary **-f csv excel**
Output
- fosslight_log_bin_YYMMDD_HHMM.txt
- fosslight_report_bin_YYMMDD_HHMM.**csv**
- fosslight_report_bin_YYMMDD_HHMM.**xlsx**
Example 4)
Command : $fosslight_binary **-o abc/output.json -f csv excel**
Error : 
> Format error - The format of output file(-o:'abc/output.json') should be in the format list(-f:'['csv', 'excel']'). …
=> Enable multiple input for -f option

requirements.txt, src/fosslight_binary/_binary.py, src/fosslight_binary/_binary_dao.py, src/fosslight_binary/_jar_analysis.py, src/fosslight_binary/binary_analysis.py
=> Refactoring OSS Item classes

requirements.txt, src/fosslight_binary/_binary.py, src/fosslight_binary/binary_analysis.py, src/fosslight_binary/cli.py
=> Support spdx

src/fosslight_binary/_simple_mode.py, src/fosslight_binary/binary_analysis.py, src/fosslight_binary/cli.py
- Apply simple mode
- Default file name 
- if binary is present, binary_list_[datemtile].txt
- if compressed is present, compressed_list_[datemtile].txt
- Exclude at simple mode
- Exclude value is 'True'
- Image, Font file
- *source.jar
- compressed file
- Exclude file beginning with '.'
=> Apply simple mode

requirements.txt, src/fosslight_binary/cli.py
=> Fix the notice screen

src/fosslight_binary/_binary.py, src/fosslight_binary/_binary_dao.py
Remove duplicate OSS from Binary DB.
- Duplicate condition: If oss name, oss version, and license are the same.
=> Remove duplicates from OSS information loaded from Binary DB

src/fosslight_binary/_binary.py
- Handling of exceeding max. url length(max 255 characters)
- Add log for long url
=> Handling of exceeding  max. url length

requirements.txt, src/fosslight_binary/_binary.py
- If exceeding 255 characters, print message with all urls.
- Remove duplicate url
=> Modify when exceeding the max. url length

.github/workflows/publish-release.yml, .github/workflows/pull-request.yml, requirements-dev.txt, src/fosslight_binary/_binary_dao.py, src/fosslight_binary/binary_analysis.py, src/fosslight_binary/cli.py
=> Fix workflow waring message

src/fosslight_binary/_binary.py, src/fosslight_binary/_jar_analysis.py
- Check if OssItem Instance for an OSS is already present
- Use same OssItem instance if the oss name and version are same
- Replace '+=' to '=' when append comment
=> Remove the duplicated comment

src/fosslight_binary/_binary_dao.py
- Remove SQL injection vulnerability
- Forward to parameter instead of .format when using Query
- Add Database query error
=> Remove SQL injection vulnerability

src/fosslight_binary/_jar_analysis.py
- Exclude cases with only oss_ver in jar analysis
=> Exclude cases with only oss_ver in jar analysis

src/fosslight_binary/_binary.py, src/fosslight_binary/_jar_analysis.py
- Copy OSS info for same checksum file
=> Copy OSS info for same checksum file

src/fosslight_binary/_binary.py, src/fosslight_binary/_jar_analysis.py, src/fosslight_binary/binary_analysis.py
Exclude package dirs with directory name
=> Exclude package dirs with directory name
